version: '3.8'
name: url-shortner

services:
  postgres-shortner-url:
    image: postgres:13
    container_name: postgres-shortner-url
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATA}
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  url-shortner-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortner-api
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres-shortner-url:5432/${DB_DATA}
      DB_PORT: 5432
      JWT_SECRET: secret
      BASE_URL: http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres-shortner-url
    networks:
      - postgres-network

networks:
  postgres-network:
