version: '3.8'

services:
  postgres-data:
    image: postgres:13
    container_name: postgres-shortner-url
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATA}
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  url-shortner-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortner-api
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATA: ${DB_DATA}
      DB_HOST: postgres-data
      DB_PORT: 5432
    ports:
      - '3000:3000'
    depends_on:
      - postgres-data
    networks:
      - postgres-network

networks:
  postgres-network:
